### ISSUE TITLE
BrokenPipeError on Unix systems when streaming larger websites

### ISSUE THREAD

**Issue by causztic** [causztic/pytor-browser#12]
When streaming larger websites, one of the relays will break and throw a BrokenPipeError.
Setup as usual:

```
python directory.py
python relay.py a
python relay.py b
python relay.py c
python client.py
```
Go to http://localhost:27182?url=https://www.google.com on a Unix machine.

**Comment by ericywl** [comment]
After some tests, I come to the conclusion that `BrokenPipeError` is actually a consequence of the `pickle.UnpicklingError` problem. It seems that if the client socket does not close, `BrokenPipeError` does not actually happen. And the socket closing was due to the `UnpicklingError`. 

What causes the `UnpicklingError` is actually the non-arrival of some packets. Going to  http://localhost:27182?url=https://www.google.com, the third relay partitions the Google response to 56 packets, each of length 4k+. However, only 52+- packets are being received by the second relay etc. In my N number of tests, only 1 got the full Google webpage. One way to solve it now is to introduce sequence number, possibly into the cell, and then do retransmission or smth...

**Comment by ericywl** [comment]
To add-on to the previous comment, I have found the reason why packets are "disappearing". The client uses `sock.recv(4790)` to receive the packet stream, which looks fine at first sight. But possibly due to some TCP optimization, some packets are concatenated together before sending. So in this case, the client would only receive the first part of the concatenated. However, we can't just increase the buffer size, cause our implementation here simply doesn't allow us.
